import {Renderer,defaults,imageFrom} from './renderer.js';
const $=id=>document.getElementById(id), c={...defaults}, renderer=new Renderer();
const BACKGROUNDS=[{id:'rooftop',name:'屋上テラス',src:'/assets/rooftop.jpg'},{id:'beach',name:'夕暮れの海辺',src:'/assets/beach.jpg'},{id:'park',name:'公園の芝生',src:'/assets/park.jpg'}];
let ready=false,playing=true,t=0,last=0,exporting=false,cancelled=false,info,job,background={...BACKGROUNDS[0]};
const specs={bgZoom:['背景の拡大',100,200,1,'%'],bgX:['背景の横位置',-100,100,1,'%'],bgY:['背景の縦位置',-100,100,1,'%'],blur:['背景のぼかし',0,20,.5,''],brightness:['背景の明るさ',30,140,1,'%'],x:['左右の位置',-20,120,.5,'%'],y:['上下の位置',40,160,.5,'%'],size:['サイズ',40,160,1,'%'],body:['体の揺れ',0,8,.1,'°'],head:['頭の揺れ',0,4,.1,'°'],hair:['髪の揺れ',0,20,.5,'°'],chest:['胸元の揺れ',0,70,1,''],cycle:['揺れの周期',.6,6,.1,'秒']};
for(const [panel,keys] of [['bgControls',['bgZoom','bgX','bgY','blur','brightness']],['placementControls',['x','y','size']],['motionControls',['body','head','hair','chest','cycle']]])for(const key of keys){
 const [label,min,max,step,unit]=specs[key],div=document.createElement('div');div.className='control';div.innerHTML=`<div class="control-top"><label for="range-${key}">${label}</label><span class="value"><input type="number" aria-label="${label}の数値" data-setting="${key}" min="${min}" max="${max}" step="${step}"><small>${unit}</small></span></div><input id="range-${key}" type="range" data-setting="${key}" min="${min}" max="${max}" step="${step}">`;$(panel).append(div);
}
function sync(){document.querySelectorAll('[data-setting]').forEach(el=>{if(el.type==='checkbox')el.checked=c[el.dataset.setting];else if(el.type!=='number'||el!==document.activeElement)el.value=c[el.dataset.setting]});$('timeline').max=c.duration;$('modeImage').classList.toggle('active',c.bgMode==='image');$('modeColor').classList.toggle('active',c.bgMode==='color');$('bgControls').style.opacity=c.bgMode==='image'?1:.45;}
function clean(settings){const out={...defaults};for(const k in defaults){const v=settings[k];if(specs[k]&&Number.isFinite(v))out[k]=Math.min(specs[k][2],Math.max(specs[k][1],v));else if(k==='blink'&&typeof v==='boolean')out[k]=v;else if(k==='color'&&/^#[0-9a-f]{6}$/i.test(v))out[k]=v;else if(k==='bgMode'&&['image','color'].includes(v))out[k]=v;else if(k==='duration'&&[2,4,8,12,20,30,60].includes(v))out[k]=v;else if(k==='fps'&&[24,30,60].includes(v))out[k]=v;else if(k==='resolution'&&[720,1080].includes(v))out[k]=v;}return out;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3500);}
function deselect(){document.querySelectorAll('[data-preset]').forEach(e=>e.classList.remove('selected'));}
document.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener('input',()=>{if(exporting)return;const k=el.dataset.setting;if(el.type==='number'&&(el.value===''||Number(el.value)<specs[k][1]||Number(el.value)>specs[k][2]))return;c[k]=el.type==='checkbox'?el.checked:k==='color'?el.value:Number(el.value);Object.assign(c,clean(c));t=Math.min(t,c.duration);sync();if(['body','head','hair','chest','cycle','blink'].includes(k))deselect();}));
document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===el));$('scenePanel').hidden=el.dataset.tab!=='scene';$('motionPanel').hidden=el.dataset.tab!=='motion';});
const presets={soft:{body:1.5,head:.6,hair:4,chest:12,cycle:3,blink:true},standard:{body:4,head:1.3,hair:10,chest:38,cycle:2,blink:true},strong:{body:6,head:2,hair:16,chest:56,cycle:1.6,blink:true},still:{body:0,head:0,hair:0,chest:0,blink:false}};
document.querySelectorAll('[data-preset]').forEach(el=>el.onclick=()=>{if(exporting)return;Object.assign(c,presets[el.dataset.preset]);deselect();el.classList.add('selected');sync();});
function play(){if(exporting)return;playing=!playing;$('play').textContent=playing?'Ⅱ':'▶';}
$('play').onclick=play;$('rewind').onclick=()=>t=0;$('timeline').oninput=e=>{t=Number(e.target.value);playing=false;$('play').textContent='▶';};
$('reset').onclick=()=>{for(const k of ['x','y','size','body','head','hair','chest','cycle','blink'])c[k]=defaults[k];sync();deselect();};$('center').onclick=()=>{c.x=50;sync();};
$('modeImage').onclick=()=>{c.bgMode='image';sync();};$('modeColor').onclick=()=>{c.bgMode='color';sync();};
async function setBackground(bg){const im=await imageFrom(bg.src);if(im.width*im.height>50000000)throw Error('背景画像は5000万画素以下にしてください');renderer.setBackground(im);background=bg;$('bgThumb').src=bg.src;$('bgName').textContent=bg.name;}
const readData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('ファイルを読み込めません'));r.readAsDataURL(file);});
async function upload(file){if(exporting||!file)return;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>30*1024*1024)throw Error('30MB以下のJPG・PNG・WebP画像を選んでください');await setBackground({name:file.name,src:await readData(file)});Object.assign(c,{bgMode:'image',bgZoom:100,bgX:0,bgY:0});sync();toast('背景を変更しました');}catch(e){toast(e.message);}}
$('uploadBg').onclick=()=>$('backgroundFile').click();$('backgroundFile').onchange=e=>upload(e.target.files[0]);$('stage').ondragover=e=>{e.preventDefault();};$('stage').ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files[0]);};
async function pickPreset(bg){if(exporting)return;try{await setBackground({...bg});for(const k of ['bgMode','bgZoom','bgX','bgY','blur','brightness'])c[k]=defaults[k];sync();}catch(e){toast(e.message);}}
for(const bg of BACKGROUNDS){const b=document.createElement('button');b.className='bg-preset';b.title=bg.name;b.setAttribute('aria-label',bg.name);b.innerHTML=`<img src="${bg.src}" alt=""><span>${bg.name}</span>`;b.onclick=()=>pickPreset(bg);$('bgPresets').append(b);}
$('defaultBg').onclick=()=>pickPreset(BACKGROUNDS[0]);
let drag;
$('preview').onpointerdown=e=>{if(exporting)return;drag={px:e.clientX,py:e.clientY,x:c.x,y:c.y};e.target.setPointerCapture(e.pointerId);$('dragHint').hidden=true;};
$('preview').onpointermove=e=>{if(!drag||exporting)return;const r=e.target.getBoundingClientRect();c.x=Math.max(-20,Math.min(120,drag.x+(e.clientX-drag.px)/r.width*100));c.y=Math.max(40,Math.min(160,drag.y+(e.clientY-drag.py)/r.height*100));sync();};
$('preview').onpointerup=$('preview').onpointercancel=()=>drag=null;
$('preview').addEventListener('wheel',e=>{e.preventDefault();if(exporting)return;c.size=Math.max(40,Math.min(160,c.size-e.deltaY*.04));sync();},{passive:false});
$('preview').onkeydown=e=>{if(exporting)return;const d=e.shiftKey?5:1;if(e.code==='Space'){e.preventDefault();play();}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){e.preventDefault();c.x+=e.code==='ArrowLeft'?-d:e.code==='ArrowRight'?d:0;c.y+=e.code==='ArrowUp'?-d:e.code==='ArrowDown'?d:0;Object.assign(c,clean(c));sync();}};
function saveBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('saveProject').onclick=()=>saveBlob(new Blob([JSON.stringify({format:'motion-studio',version:1,settings:c,background},null,2)],{type:'application/json'}),'motion-studio-settings.json');
$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>42*1024*1024)throw Error('設定ファイルが大きすぎます');const p=JSON.parse(await f.text());if(p.format!=='motion-studio'||p.version!==1||!p.settings||!p.background||!(BACKGROUNDS.some(b=>b.src===p.background.src)||/^data:image\/(png|jpeg|webp);base64,/.test(p.background.src)))throw Error('Motion Studioの設定ファイルを選んでください');await setBackground({name:String(p.background.name).slice(0,200),src:p.background.src});Object.assign(c,clean(p.settings));t=0;sync();deselect();toast('背景と設定を復元しました');}catch(e){toast(e.message);}e.target.value='';};
async function api(url,data){const res=await fetch(url,{method:'POST',headers:{'X-Studio-Token':info.token,'Content-Type':data instanceof Blob?'image/jpeg':'application/json'},body:data instanceof Blob?data:JSON.stringify(data||{})});const answer=await res.json();if(!res.ok)throw Error(answer.error||'書き出しに失敗しました');return answer;}
const pause=ms=>new Promise(r=>setTimeout(r,ms));
$('cancelExport').onclick=()=>{cancelled=true;$('exportText').textContent='停止しています…';};
async function exportVideo(){if(!ready||exporting)return;exporting=true;cancelled=false;job=null;const wasPlaying=playing,snapshot={...c};playing=false;document.body.classList.add('exporting');document.querySelectorAll('button,input,select').forEach(el=>{if(el.id!=='cancelExport')el.disabled=true;});$('export').disabled=true;$('exportProgress').hidden=false;$('download').hidden=true;$('exportError').hidden=true;$('progress').value=0;const canvas=document.createElement('canvas');canvas.height=snapshot.resolution;canvas.width=snapshot.resolution*16/9;
 try{job=await api('/api/export',{width:canvas.width,height:canvas.height,fps:snapshot.fps,duration:snapshot.duration});for(let i=0;i<job.total;i++){if(cancelled)break;renderer.render(canvas,i/snapshot.fps,snapshot);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.97));if(!blob)throw Error('フレームを生成できません');await api(`/api/export/${job.id}/frame?index=${i}`,blob);$('progress').value=(i+1)/job.total;$('exportText').textContent=`フレームを描画中 ${Math.round((i+1)/job.total*100)}%（${i+1} / ${job.total}）`;}
 if(cancelled){await api(`/api/export/${job.id}/cancel`);toast('書き出しをキャンセルしました');return;}
 await api(`/api/export/${job.id}/finish`);$('exportText').textContent='MP4を仕上げています…';let state;do{if(cancelled){await api(`/api/export/${job.id}/cancel`);toast('書き出しをキャンセルしました');return;}await pause(400);const res=await fetch(`/api/export/${job.id}`);state=await res.json();}while(state.state==='encoding');if(state.state!=='done')throw Error(state.error||'書き出しに失敗しました');$('download').href=state.url;$('download').download=job.id+'.mp4';$('download').hidden=false;$('status').textContent=`保存完了：${info.outputFolder}\\${job.id}.mp4`;toast('MP4を保存しました');
 }catch(e){if(job)try{await api(`/api/export/${job.id}/cancel`);}catch{}$('exportError').textContent=e.message;$('exportError').hidden=false;}finally{exporting=false;playing=wasPlaying;last=0;document.body.classList.remove('exporting');document.querySelectorAll('button,input,select').forEach(el=>el.disabled=false);$('export').disabled=!info.ffmpeg;$('exportProgress').hidden=true;canvas.width=canvas.height=1;}}
$('export').onclick=exportVideo;
function tick(now){if(ready&&!exporting){if(playing&&last)t=(t+Math.min((now-last)/1000,.1))%c.duration;try{renderer.render($('preview'),t,c);}catch(e){ready=false;playing=false;$('status').textContent=e.message;$('export').disabled=true;}$('timeLabel').textContent=`${t.toFixed(2)} / ${c.duration.toFixed(2)}`;$('timeline').value=t;}last=now;requestAnimationFrame(tick);}
sync();requestAnimationFrame(tick);
try{const results=await Promise.all([fetch('/api/info').then(r=>r.json()),renderer.load(),setBackground(background)]);info=results[0];ready=true;$('loading').hidden=true;$('export').disabled=!info.ffmpeg;$('status').textContent=info.ffmpeg?'プレビュー再生中 · 背景と動きを自由に調整できます':'FFmpegが見つからないためMP4出力は利用できません';}catch(e){$('loading').textContent=e.message;$('status').textContent='読み込みに失敗しました。再読み込みしてください';}
window.studio={getState:()=>({...c}),setState:s=>{Object.assign(c,clean({...c,...s}));sync();},renderAt:time=>{playing=false;t=time;renderer.render($('preview'),t,c);},exportVideo,get ready(){return ready;},get exporting(){return exporting;}};
